server:
  port: 8080

spring:
  application:
    name: authentication-service


  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  private-key: classpath:keys/private.pem
  expiration: 3600000  # 1 hour
