
server:
  port: 8081

spring:
  application:
    name: user-management-service


  datasource:
    url: jdbc:mysql://localhost:3306/user_management_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

jwt:
  public-key: classpath:keys/public.pem